/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


abstract  class Animal {
    abstract void  makeSound();
    void sleep(){
        System.out.println("Sleeping...");
    }

}

class  Dog extends Animal {
    @Override
    void makeSound() {
        System.out.println("Bark...");
    }
}

public class App {


    public static void main(String[] args) {

        Dog dog = new Dog();
        dog.sleep();
        dog.makeSound();
    }
}
